services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_up.py
    envVars:
      - key: OPEN_AI_API_KEY
      - key: BOT_TOKEN
